# Generated by Django 5.1.1 on 2024-09-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0002_customuser_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_code",
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
