# Generated by Django 5.1.1 on 2024-09-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0003_alter_course_course_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "student"), (2, "faculty"), (3, "staff")], null=True
            ),
        ),
    ]
