# Generated by Django 5.1.1 on 2024-09-23 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0004_customuser_user_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("number", "course")},
        ),
        migrations.CreateModel(
            name="StudentEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="panel.section"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="panel.student"
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "section")},
            },
        ),
    ]
